name: Publish Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0)'
        required: true
      is_first_publish:
        description: 'Is this the first time publishing the package?'
        required: true
        type: boolean
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install composer dependencies
        run: composer install --no-dev --no-progress --no-interaction

      - name: First-time package submission to Packagist
        if: ${{ github.event.inputs.is_first_publish == 'true' }}
        run: |
          echo "Submitting package for the first time to Packagist"
          curl -X POST \
            -H "content-type:application/json" \
            -d '{"repository":{"url":"https://github.com/changerawr/php"}}' \
            "https://packagist.org/api/submit-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_API_TOKEN }}"
          echo "Package submitted. Please check Packagist for confirmation."
          echo "Note: It might take a few minutes for Packagist to process the submission."

      - name: Update existing package on Packagist
        if: ${{ github.event.inputs.is_first_publish == 'false' }}
        run: |
          echo "Updating existing package for version ${{ github.event.inputs.version }}"
          curl -X POST \
            -H "content-type:application/json" \
            -d '{"repository":{"url":"https://github.com/changerawr/php"}}' \
            "https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_API_TOKEN }}"
          echo "Package update triggered. Please check Packagist for confirmation."